[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200

; Задаем правильный размер Flash
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
; Говорим использовать нашу таблицу разделов
board_build.partitions = partitions.csv